Gp 67 new hello spring framework (for web) exercise main
bobocode-projects/java-web-course pull request #10
Opened 2021-04-05 09:50 UTC by mathodcoast

2021-04-07 08:17 UTC, tboychuk approved these changes

2021-04-07 08:18 UTC, tboychuk requested changes
The only one critical thing that should be fixed before merge is JPA dependency and those JPA entities

2021-04-07 08:20 UTC, mathodcoast commented on java-web-course-util/spring-framework-exercises-model/pom.xml
> +            <groupId>org.hibernate.javax.persistence</groupId>
@tboychuk Removing will break util class

2021-04-10 09:10 UTC, mathodcoast commented on 3-0-spring-framework/3-0-0-hello-spring-framework/src/test/java/com/bobocode/ApplicationContextTest.java
> +    void findRichestAccount() {
@tboychuk but we don't have main

2021-04-13 06:31 UTC, tboychuk approved these changes

2021-04-13 06:31 UTC, merged